### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by ufechner7** [JuliaControl/SymbolicControlSystems.jl#13]
Perhaps https://github.com/robertobucher/pysimCoder can be used as inspiration for adding a GUI?

**Comment by baggepinnen** [comment]
Adding a GUI is
1. An incredible effort, likely to require several person years to make robust
2. Not related to the functionality in this package.

There is a GUI being worked on for ModelingToolkit that would fill this role, but due to point 1 above, it will likely take quite a long time before it's available.

**Comment by ufechner7** [comment]
> 1. An incredible effort, likely to require several person years to make robust
That is correct, but pysimCoder is an example for GUI that was mainly developed by one person and has now a group of contributors, so it is an example that this is manageable as open source project. And porting code from Python to Julia is a lot less effort than writing code from the scratch...

> 2. Not related to the functionality in this package.
Well, pysimCoder generates C code for control systems which this package also does. But of course it is up to you to define the scope of this package.
